Repository AleksGoodOmens/RIP, pull requests merged in 2025-09, with the labels that each got.

#73 test: add test for response page
  src/app/[locale]/rest-client/[...url]/@response/page.test.tsx
Labels: TASK

#74 9 task implement history and analytics with server side generation
  jest.config.ts
  messages/en.json
  messages/ru.json
  package.json
  src/app/[locale]/authentification/loading.tsx
  src/app/[locale]/authentification/login/loading.tsx
  src/app/[locale]/authentification/page.tsx
  src/app/[locale]/authentification/register/loading.tsx
  src/app/[locale]/loading.tsx
  src/app/[locale]/rest-client/[...url]/@response/page.test.tsx
  src/app/[locale]/rest-client/[...url]/@response/page.tsx
  src/app/[locale]/rest-client/[...url]/action.test.tsx
  src/app/[locale]/rest-client/[...url]/action.ts
  src/app/[locale]/rest-client/[...url]/page.tsx
  src/app/[locale]/rest-client/history/page.tsx
  src/app/[locale]/rest-client/layout.tsx
  src/app/[locale]/rest-client/loading.tsx
  src/app/api/history/route.ts
  src/app/api/variables/variables.test.ts
  src/app/api/variables/variables.ts
  src/components/history-client/HistoryClient.tsx
  src/components/history-empty/HistoryEmpty.tsx
  src/components/history-full/HistoryFull.tsx
  src/components/index.ts
  src/components/rest-client/RestClient.test.tsx
  src/components/rest-client/RestClient.tsx
  src/components/variables-client/VariablesClient.tsx
  src/firebase/firebase.ts
  src/interfaces/index.tsx
  src/lib/api-request.ts
  src/lib/variables-server.test.ts
  src/lib/variables-server.ts
  src/utils/hooks/useVariablePairs.ts
  src/utils/hooks/useVariables.ts
  tsconfig.json
Labels: FEATURE

#75 feat: history page tests
  jest.config.ts
  src/app/[locale]/rest-client/history/historyPage.test.tsx
  src/app/[locale]/rest-client/loading.tsx
  src/app/api/history/route.test.tsx
  src/app/api/history/route.ts
  src/components/history-client/HistoryClient.test.tsx
  src/components/history-empty/HistoryEmpty.test.tsx
  src/components/history-full/HistoryFull.test.tsx
Labels: documentation
